import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Scanner;

// Java program to calculate SHA hash value

public class Q4 {
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException
    {
        // Static getInstance method is called with hashing SHA
        MessageDigest md = MessageDigest.getInstance("SHA-256");

        // digest() method called
        // to calculate message digest of an input
        // and return array of byte
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }
    
    public static String toHexString(byte[] hash)
    {
        // Convert byte array into signum representation
        BigInteger number = new BigInteger(1, hash);

        // Convert message digest into hex value
        StringBuilder hexString = new StringBuilder(number.toString(16));

        // Pad with leading zeros
        while (hexString.length() < 64)
        {
            hexString.insert(0, '0');
        }

        return hexString.toString();
    }

    // Driver code
    public static void main(String args[])
    {
        String hash = "940c9f61c30cd83b6e3d0a1826d446f4426451a873feedcbb7d0ddf8fa51919b";
        String salt = "pjAmPOYT9jo5";
        File myObj = new File("words_alpha.txt");
        HashMap<String,String> english_words = new HashMap<String,String>();

        try (Scanner myReader = new Scanner(myObj)) {
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                //english_words.put(data, data);

                String hashedValue = toHexString(getSHA(data));
            }
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        }



        // try
        // {
        //     System.out.println("HashCode Generated by SHA-256 for:");

        //     String s1 = "GeeksForGeeks";
        //     System.out.println("\n" + s1 + " : " + toHexString(getSHA(s1)));

        //     String s2 = "hello world";
        //     System.out.println("\n" + s2 + " : " + toHexString(getSHA(s2)));
            
        //     String s3 = "K1t4fo0V"; 
        //     System.out.println("\n" + s3 + " : " + toHexString(getSHA(s3)));
        // }
        // // For specifying wrong message digest algorithms
        // catch (NoSuchAlgorithmException e) {
        //     System.out.println("Exception thrown for incorrect algorithm: " + e);
        // }
    }
}